ALTER TABLE "knowledge_analysis_report" DROP CONSTRAINT "knowledge_analysis_report_hash_check";--> statement-breakpoint
ALTER TABLE "knowledge_analysis_report" DROP CONSTRAINT "knowledge_analysis_report_state_check";--> statement-breakpoint
ALTER TABLE "knowledge_analysis_report" ADD COLUMN "report_series_id" uuid DEFAULT gen_random_uuid() NOT NULL;--> statement-breakpoint
ALTER TABLE "knowledge_analysis_report" ADD COLUMN "version" integer DEFAULT 1 NOT NULL;--> statement-breakpoint
ALTER TABLE "knowledge_analysis_report" ADD COLUMN "supersedes_report_id" uuid;--> statement-breakpoint
ALTER TABLE "knowledge_analysis_report" ADD COLUMN "interactive_byte_count" integer;--> statement-breakpoint
ALTER TABLE "knowledge_analysis_report" ADD COLUMN "interactive_script_hash" varchar(64);--> statement-breakpoint
ALTER TABLE "knowledge_analysis_report" ADD COLUMN "static_byte_count" integer;--> statement-breakpoint
ALTER TABLE "knowledge_analysis_report" ADD CONSTRAINT "knowledge_analysis_report_supersedes_fk" FOREIGN KEY ("supersedes_report_id") REFERENCES "public"."knowledge_analysis_report"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "knowledge_analysis_report_series_version_unique" ON "knowledge_analysis_report" USING btree ("report_series_id","version");--> statement-breakpoint
CREATE UNIQUE INDEX "knowledge_analysis_report_supersedes_unique" ON "knowledge_analysis_report" USING btree ("supersedes_report_id");--> statement-breakpoint
ALTER TABLE "knowledge_analysis_report" ADD CONSTRAINT "knowledge_analysis_report_version_check" CHECK ("knowledge_analysis_report"."version" > 0 and (("knowledge_analysis_report"."version" = 1 and "knowledge_analysis_report"."supersedes_report_id" is null) or ("knowledge_analysis_report"."version" > 1 and "knowledge_analysis_report"."supersedes_report_id" is not null)));--> statement-breakpoint
ALTER TABLE "knowledge_analysis_report" ADD CONSTRAINT "knowledge_analysis_report_size_check" CHECK (("knowledge_analysis_report"."interactive_byte_count" is null or "knowledge_analysis_report"."interactive_byte_count" between 1 and 2097152) and ("knowledge_analysis_report"."static_byte_count" is null or "knowledge_analysis_report"."static_byte_count" between 1 and 2097152));--> statement-breakpoint
ALTER TABLE "knowledge_analysis_report" ADD CONSTRAINT "knowledge_analysis_report_hash_check" CHECK (("knowledge_analysis_report"."interactive_content_hash" is null or "knowledge_analysis_report"."interactive_content_hash" ~ '^[0-9a-f]{64}$') and ("knowledge_analysis_report"."interactive_script_hash" is null or "knowledge_analysis_report"."interactive_script_hash" ~ '^[0-9a-f]{64}$') and ("knowledge_analysis_report"."static_content_hash" is null or "knowledge_analysis_report"."static_content_hash" ~ '^[0-9a-f]{64}$'));--> statement-breakpoint
ALTER TABLE "knowledge_analysis_report" ADD CONSTRAINT "knowledge_analysis_report_state_check" CHECK (("knowledge_analysis_report"."status" in ('queued', 'planning', 'computing', 'rendering') and "knowledge_analysis_report"."completed_at" is null and "knowledge_analysis_report"."structured_report" is null and "knowledge_analysis_report"."interactive_storage_key" is null and "knowledge_analysis_report"."interactive_content_hash" is null and "knowledge_analysis_report"."interactive_byte_count" is null and "knowledge_analysis_report"."interactive_script_hash" is null and "knowledge_analysis_report"."static_storage_key" is null and "knowledge_analysis_report"."static_content_hash" is null and "knowledge_analysis_report"."static_byte_count" is null and "knowledge_analysis_report"."safe_error_code" is null and "knowledge_analysis_report"."safe_error_summary" is null) or ("knowledge_analysis_report"."status" = 'succeeded' and "knowledge_analysis_report"."completed_at" is not null and "knowledge_analysis_report"."agent_run_id" is not null and "knowledge_analysis_report"."structured_report" is not null and "knowledge_analysis_report"."interactive_storage_key" is not null and "knowledge_analysis_report"."interactive_content_hash" is not null and "knowledge_analysis_report"."interactive_byte_count" is not null and "knowledge_analysis_report"."interactive_script_hash" is not null and "knowledge_analysis_report"."static_storage_key" is not null and "knowledge_analysis_report"."static_content_hash" is not null and "knowledge_analysis_report"."static_byte_count" is not null and "knowledge_analysis_report"."safe_error_code" is null and "knowledge_analysis_report"."safe_error_summary" is null) or ("knowledge_analysis_report"."status" = 'failed' and "knowledge_analysis_report"."completed_at" is not null and "knowledge_analysis_report"."safe_error_code" is not null and "knowledge_analysis_report"."safe_error_summary" is not null));